# Generated by Django 4.1.3 on 2022-11-15 14:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.CharField(max_length=512)),
                ('envs', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=[], size=None)),
                ('command', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
